/**
 * The flavour lists and the generation-4 dexes, verbatim from the old bot's
 * `PokeInfo.ts` (the chat copy viewers know). Species names are `@pkmn`
 * names; `Dex.forGen(4).species.get()` resolves every entry.
 */

/** How a Pokémon roars: `…roared <this>`. */
export const POKE_ROAR_ACTIONS: readonly string[] = [
    'as it tore through the house.',
    'at the scent of real food.',
    'awake, thirsty and demanding.',
    'again and beat on the walls.',
    `and slammed its' fists against the ground.`,
    `with fury and pain until its' throat was raw.`,
    'impressively as they entered the clearing at the mill site.',
    `and slammed its' hands on the desk at the far end of the library, unable to stop the images racing through its' mind.`,
    'loud enough to shake the door.',
    'on the tin roof and plunged off the eves, where the wind caught it and drove it across the yard in horizontal sheets.',
    `in through the ceiling, hail and water pelting its' body, deafened by thunder.`,
    `its' engine as it turned the truck around, and slung gravel on the road as it took off.`,
    `out at once: Oo-oo-oo-oo!`,
    `"I am British" at which the entire room erupted in applause.`,
    `and refused to bow.`,
    `and the band played the fight song.`,
    `at its' body's reaction to the food.`,
    `to life at the scent of its' dark spices while it fought the urge to break down into hysterics.`,
];

/** Every base species through generation 4 — what a `Pokemon Create` redeem rolls from. */
export const GEN4_POKEDEX: readonly string[] = [
    'Milotic',
    'Rotom',
    'Bulbasaur',
    'Ivysaur',
    'Venusaur',
    'Charmander',
    'Charmeleon',
    'Charizard',
    'Squirtle',
    'Wartortle',
    'Blastoise',
    'Butterfree',
    'Beedrill',
    'Pidgeot',
    'Pikachu',
    'Raichu',
    'Nidoqueen',
    'Nidoking',
    'Clefairy',
    'Clefable',
    'Jigglypuff',
    'Wigglytuff',
    'Vileplume',
    'Poliwrath',
    'Alakazam',
    'Victreebel',
    'Golem',
    'Mr. Mime',
    'Articuno',
    'Zapdos',
    'Moltres',
    'Chikorita',
    'Bayleef',
    'Meganium',
    'Cyndaquil',
    'Quilava',
    'Typhlosion',
    'Totodile',
    'Croconaw',
    'Feraligatr',
    'Igglybuff',
    'Togepi',
    'Togetic',
    'Cleffa',
    'Ampharos',
    'Bellossom',
    'Marill',
    'Azumarill',
    'Jumpluff',
    'Snubbull',
    'Granbull',
    'Tyrogue',
    'Hitmonlee',
    'Hitmonchan',
    'Hitmontop',
    'Treecko',
    'Grovyle',
    'Sceptile',
    'Torchic',
    'Combusken',
    'Blaziken',
    'Mudkip',
    'Marshtomp',
    'Swampert',
    'Beautifly',
    'Ralts',
    'Kirlia',
    'Gardevoir',
    'Exploud',
    'Azurill',
    'Mawile',
    'Plusle',
    'Minun',
    'Kecleon',
    'Feebas',
    'Duskull',
    'Dusclops',
    'Regirock',
    'Regice',
    'Registeel',
    'Turtwig',
    'Grotle',
    'Torterra',
    'Chimchar',
    'Monferno',
    'Infernape',
    'Piplup',
    'Prinplup',
    'Empoleon',
    'Starly',
    'Staraptor',
    'Roserade',
    'Mime Jr.',
    'Togekiss',
    'Dusknoir',
    'Arbok',
    'Dugtrio',
    'Farfetch’d',
    'Dodrio',
    'Gengar',
    'Electrode',
    'Exeggutor',
    'Noctowl',
    'Ariados',
    'Qwilfish',
    'Magcargo',
    'Corsola',
    'Mantine',
    'Raikou',
    'Entei',
    'Suicune',
    'Swellow',
    'Wingull',
    'Pelipper',
    'Masquerain',
    'Delcatty',
    'Volbeat',
    'Illumise',
    'Torkoal',
    'Lunatone',
    'Solrock',
    'Castform',
    'Chimecho',
    'Burmy',
    'Wormadam',
    'Cherrim',
    'Arceus',
    'Koffing',
    'Weezing',
    'Trapinch',
    'Vibrava',
    'Flygon',
    'Magnezone',
    'Leafeon',
    'Glaceon',
    'Gallade',
    'Heatran',
    'Caterpie',
    'Metapod',
    'Weedle',
    'Kakuna',
    'Pidgey',
    'Pidgeotto',
    'Rattata',
    'Raticate',
    'Spearow',
    'Fearow',
    'Ekans',
    'Sandshrew',
    'Sandslash',
    'Nidoran-F',
    'Nidorina',
    'Nidoran-M',
    'Nidorino',
    'Vulpix',
    'Ninetales',
    'Zubat',
    'Golbat',
    'Oddish',
    'Gloom',
    'Paras',
    'Parasect',
    'Venonat',
    'Venomoth',
    'Diglett',
    'Meowth',
    'Persian',
    'Psyduck',
    'Golduck',
    'Mankey',
    'Primeape',
    'Growlithe',
    'Arcanine',
    'Poliwag',
    'Poliwhirl',
    'Abra',
    'Kadabra',
    'Machop',
    'Machoke',
    'Machamp',
    'Bellsprout',
    'Weepinbell',
    'Tentacool',
    'Tentacruel',
    'Geodude',
    'Graveler',
    'Ponyta',
    'Rapidash',
    'Slowpoke',
    'Slowbro',
    'Magnemite',
    'Magneton',
    'Doduo',
    'Seel',
    'Dewgong',
    'Grimer',
    'Muk',
    'Shellder',
    'Cloyster',
    'Gastly',
    'Haunter',
    'Onix',
    'Drowzee',
    'Hypno',
    'Krabby',
    'Kingler',
    'Voltorb',
    'Exeggcute',
    'Cubone',
    'Marowak',
    'Lickitung',
    'Rhyhorn',
    'Rhydon',
    'Chansey',
    'Tangela',
    'Kangaskhan',
    'Horsea',
    'Seadra',
    'Goldeen',
    'Seaking',
    'Staryu',
    'Starmie',
    'Scyther',
    'Jynx',
    'Electabuzz',
    'Magmar',
    'Pinsir',
    'Tauros',
    'Magikarp',
    'Gyarados',
    'Lapras',
    'Ditto',
    'Eevee',
    'Vaporeon',
    'Jolteon',
    'Flareon',
    'Porygon',
    'Omanyte',
    'Omastar',
    'Kabuto',
    'Kabutops',
    'Aerodactyl',
    'Snorlax',
    'Dratini',
    'Dragonair',
    'Dragonite',
    'Mewtwo',
    'Mew',
    'Sentret',
    'Furret',
    'Hoothoot',
    'Ledyba',
    'Ledian',
    'Spinarak',
    'Crobat',
    'Chinchou',
    'Lanturn',
    'Pichu',
    'Natu',
    'Xatu',
    'Mareep',
    'Flaaffy',
    'Sudowoodo',
    'Politoed',
    'Hoppip',
    'Skiploom',
    'Aipom',
    'Sunkern',
    'Sunflora',
    'Yanma',
    'Wooper',
    'Quagsire',
    'Espeon',
    'Umbreon',
    'Murkrow',
    'Slowking',
    'Misdreavus',
    'Unown',
    'Wobbuffet',
    'Girafarig',
    'Pineco',
    'Forretress',
    'Dunsparce',
    'Gligar',
    'Steelix',
    'Scizor',
    'Shuckle',
    'Heracross',
    'Sneasel',
    'Teddiursa',
    'Ursaring',
    'Slugma',
    'Swinub',
    'Piloswine',
    'Remoraid',
    'Octillery',
    'Delibird',
    'Skarmory',
    'Houndour',
    'Houndoom',
    'Kingdra',
    'Phanpy',
    'Donphan',
    'Porygon2',
    'Stantler',
    'Smeargle',
    'Smoochum',
    'Elekid',
    'Magby',
    'Miltank',
    'Blissey',
    'Larvitar',
    'Pupitar',
    'Tyranitar',
    'Lugia',
    'Ho-Oh',
    'Celebi',
    'Poochyena',
    'Mightyena',
    'Zigzagoon',
    'Linoone',
    'Wurmple',
    'Silcoon',
    'Cascoon',
    'Dustox',
    'Lotad',
    'Lombre',
    'Ludicolo',
    'Seedot',
    'Nuzleaf',
    'Shiftry',
    'Taillow',
    'Surskit',
    'Shroomish',
    'Breloom',
    'Slakoth',
    'Vigoroth',
    'Slaking',
    'Nincada',
    'Ninjask',
    'Shedinja',
    'Whismur',
    'Loudred',
    'Makuhita',
    'Hariyama',
    'Nosepass',
    'Skitty',
    'Sableye',
    'Aron',
    'Lairon',
    'Aggron',
    'Meditite',
    'Medicham',
    'Electrike',
    'Manectric',
    'Roselia',
    'Gulpin',
    'Swalot',
    'Carvanha',
    'Sharpedo',
    'Wailmer',
    'Wailord',
    'Numel',
    'Camerupt',
    'Spoink',
    'Grumpig',
    'Spinda',
    'Cacnea',
    'Cacturne',
    'Swablu',
    'Altaria',
    'Zangoose',
    'Seviper',
    'Barboach',
    'Whiscash',
    'Corphish',
    'Crawdaunt',
    'Baltoy',
    'Claydol',
    'Lileep',
    'Cradily',
    'Anorith',
    'Armaldo',
    'Shuppet',
    'Banette',
    'Tropius',
    'Absol',
    'Wynaut',
    'Snorunt',
    'Glalie',
    'Spheal',
    'Sealeo',
    'Walrein',
    'Clamperl',
    'Huntail',
    'Gorebyss',
    'Relicanth',
    'Luvdisc',
    'Bagon',
    'Shelgon',
    'Salamence',
    'Beldum',
    'Metang',
    'Metagross',
    'Latias',
    'Latios',
    'Kyogre',
    'Groudon',
    'Rayquaza',
    'Jirachi',
    'Deoxys',
    'Staravia',
    'Bidoof',
    'Bibarel',
    'Kricketot',
    'Kricketune',
    'Shinx',
    'Luxio',
    'Luxray',
    'Budew',
    'Cranidos',
    'Rampardos',
    'Shieldon',
    'Bastiodon',
    'Mothim',
    'Combee',
    'Vespiquen',
    'Pachirisu',
    'Buizel',
    'Floatzel',
    'Cherubi',
    'Shellos',
    'Gastrodon',
    'Ambipom',
    'Drifloon',
    'Drifblim',
    'Buneary',
    'Lopunny',
    'Mismagius',
    'Honchkrow',
    'Glameow',
    'Purugly',
    'Chingling',
    'Stunky',
    'Skuntank',
    'Bronzor',
    'Bronzong',
    'Bonsly',
    'Happiny',
    'Chatot',
    'Spiritomb',
    'Gible',
    'Gabite',
    'Garchomp',
    'Munchlax',
    'Riolu',
    'Lucario',
    'Hippopotas',
    'Hippowdon',
    'Skorupi',
    'Drapion',
    'Croagunk',
    'Toxicroak',
    'Carnivine',
    'Finneon',
    'Lumineon',
    'Mantyke',
    'Snover',
    'Abomasnow',
    'Weavile',
    'Lickilicky',
    'Rhyperior',
    'Tangrowth',
    'Electivire',
    'Magmortar',
    'Yanmega',
    'Gliscor',
    'Mamoswine',
    'Porygon-Z',
    'Probopass',
    'Froslass',
    'Uxie',
    'Mesprit',
    'Azelf',
    'Dialga',
    'Palkia',
    'Regigigas',
    'Giratina',
    'Cresselia',
    'Phione',
    'Manaphy',
    'Darkrai',
    'Shaymin',
];

/** The species the random chat drops pick from. */
export const GEN4_DROPS_POKEDEX: readonly string[] = [
    'Milotic',
    'Venusaur',
    'Charizard',
    'Blastoise',
    'Pikachu',
    'Jigglypuff',
    'Alakazam',
    'Articuno',
    'Zapdos',
    'Moltres',
    'Typhlosion',
    'Feraligatr',
    'Togepi',
    'Sceptile',
    'Blaziken',
    'Swampert',
    'Gardevoir',
    'Regirock',
    'Regice',
    'Registeel',
    'Torterra',
    'Infernape',
    'Empoleon',
    'Raikou',
    'Entei',
    'Suicune',
    'Arceus',
    'Magnezone',
    'Leafeon',
    'Glaceon',
    'Heatran',
    'Meowth',
    'Psyduck',
    'Arcanine',
    'Geodude',
    'Muk',
    'Onix',
    'Scyther',
    'Gyarados',
    'Eevee',
    'Vaporeon',
    'Jolteon',
    'Flareon',
    'Aerodactyl',
    'Mewtwo',
    'Mew',
    'Sudowoodo',
    'Espeon',
    'Umbreon',
    'Skarmory',
    'Tyranitar',
    'Lugia',
    'Ho-Oh',
    'Celebi',
    'Shedinja',
    'Absol',
    'Salamence',
    'Latias',
    'Latios',
    'Kyogre',
    'Groudon',
    'Rayquaza',
    'Jirachi',
    'Deoxys',
    'Purugly',
    'Spiritomb',
    'Lucario',
    'Uxie',
    'Mesprit',
    'Azelf',
    'Dialga',
    'Palkia',
    'Regigigas',
    'Giratina',
    'Cresselia',
    'Phione',
    'Manaphy',
    'Darkrai',
    'Shaymin',
];

export const POKE_SLAUGHTER_APPROACHES: readonly string[] = [
    'tiptoed behind',
    'crept up on',
    'moon walked towards',
    'crashed from the ceiling onto',
    'dug out from beneath',
    'abruptly tackled',
    'reluctantly approached',
    'injected 400 marijuanas into',
    'plummeted sixteen feet through an announcers table onto',
];

export const POKE_SLAUGHTER_ACTIONS: readonly string[] = [
    'and karate chopped their nose off',
    'and permanently suplexed them near the office building',
    'and 360 no-scoped them',
    'and kissed them goodbye',
    `and in one swift motion, omae wa mou'd them. At least it was halal`,
    `and forced them to watch Rama's stream until the light faded from their eyes`,
    'and buried them under the oak tree',
    ', returned them to their pokeball, and threw it into the sun',
    'and pushed them into the Mariana Trench',
    `and tied balloons to them until they couldn't come back`,
    `and told them their mother never loved them`,
];

export const POKE_FAILED_CATCHES: readonly string[] = [
    `will not bow to its new leader`,
    `swatted the pokeball into the lake`,
    `swallowed your ball`,
    `doesn't like the way you smell`,
    `hid behind a bush`,
    `caught the pokeball, and took a dump in it`,
    `spat at your feet in disgust`,
    `says your ball is too small`,
    `refused to enter the pokeball with no wifi`,
    `feels you should have a higher income before bringing them into your life`,
    `watched as the pokeball missed entirely`,
    `says you throw like a Yuumi`,
    `froze time and kicked you where it hurts`,
];
